# Generated by Django 3.0.8 on 2020-07-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
