# Generated by Django 3.0.8 on 2020-07-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0003_url_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
